[webservers]
web-server-1 ansible_host=81.26.185.22 internal_ip=10.10.0.27
web-server-2 ansible_host=158.160.150.239 internal_ip=10.10.0.15
web-server-3 ansible_host=81.26.179.52 internal_ip=10.10.0.5

[proxy]
web-server-1

[nginx_servers]
web-server-2
web-server-3

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
