---
- name: Установка Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Создание кастомной страницы index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Перезапуск Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
