---
- name: Базовая настройка всех ВМ
  hosts: webservers
  become: yes
  roles:
    - vm-setup

- name: Настройка проксирующего Nginx
  hosts: proxy
  become: yes
  roles:
    - nginx-proxy

- name: Настройка отдающих Nginx
  hosts: nginx_servers
  become: yes
  roles:
    - nginx-web
